replicaCount: 1

image:
  repository: ghcr.io/kuburn/kubeidle/kubeidle
  tag: v0.17
  pullPolicy: IfNotPresent
  pullSecrets:
  - name: dockerconfigjson-github-com

startTime: "2230"
stopTime: "0800"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

rbac:
  create: true

namespaces:
  - default
  - example
