apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeidle.fullname" . }}
  labels:
    {{- include "kubeidle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubeidle.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeidle.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubeidle.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - name: metrics
              containerPort: 9095
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
          env:
            - name: START_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kubeidle.fullname" . }}-config
                  key: startTime
            - name: STOP_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kubeidle.fullname" . }}-config
                  key: stopTime
            - name: NAMESPACES
              value: {{ join "," .Values.namespaces | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets: {{ toYaml .Values.image.pullSecrets | nindent 6 }}
      {{- end}}
