apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeidle.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kubeidle.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kubeidle.name" . }}
    spec:
      serviceAccountName: {{ include "kubeidle.fullname" . }}
      containers:
        - name: kubeidle
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
          env:
            - name: START_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kubeidle.fullname" . }}-config
                  key: START_TIME
            - name: STOP_TIME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kubeidle.fullname" . }}-config
                  key: STOP_TIME
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

      {{- if .Values.nodeSelector }}
      nodeSelector: 
      {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end}}

      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end}}
 
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets: {{ toYaml .Values.image.pullSecrets | nindent 6 }}
      {{- end}}
