apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeidle.fullname" . }}
  labels:
    {{- include "kubeidle.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9095"
spec:
  type: ClusterIP
  ports:
    - port: 9095
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "kubeidle.selectorLabels" . | nindent 4 }}
